plugins {
    id 'com.infenia.jagratha.java-conventions'
    id 'com.infenia.jagratha.quality-conventions'
    id 'com.infenia.jagratha.jacoco-conventions'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

// Library module
bootJar {
    enabled = false
}
jar {
    enabled = true
}

dependencies {
    implementation project(':jagratha-plugin-api')

    // Default plugins
    implementation project(':plugins:build-tools:gradle')
    implementation project(':plugins:processors:checkstyle')
    implementation project(':plugins:ai:qwen')

    implementation libs.spring.boot.starter.webflux
    implementation libs.spring.boot.starter.validation
    implementation libs.spring.boot.starter.actuator
    implementation libs.jackson.dataformat.yaml
    implementation libs.mapstruct

    implementation libs.spring.ai.mcp.server
    implementation libs.springdoc.openapi

    annotationProcessor libs.spring.boot.configuration.processor
    annotationProcessor libs.mapstruct.processor
    annotationProcessor libs.lombok.mapstruct.binding

    testImplementation libs.spring.boot.starter.webflux.test
    testImplementation libs.spring.boot.starter.jackson.test
    testImplementation libs.reactor.test
}
