spring:
  main:
    banner-mode: "off"
  ai:
    mcp:
      server:
        name: jagratha
        version: 0.0.1
        stdio: true
  config:
    import: "optional:file:config.yaml"

logging:
  level:
    root: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n%wEx"
