spring:
  application:
    name: yukta-cli
  profiles:
    default: dev
  main:
    banner-mode: "off"

logging:
  level:
    root: INFO
    org.springframework: WARN

yukta:
  heartbeat-interval-seconds: 10
  daemon:
    port: 8080
    startup-timeout-seconds: 60
    health-check-interval-ms: 500
    jar-path: ./boot/build/libs/boot-0.0.1-SNAPSHOT.jar
  server:
    url: http://localhost:8080
