plugins {
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
    alias(libs.plugins.graalvm.buildtools.native)
    alias(libs.plugins.lombok)
}

dependencies {
    implementation project(':jagratha-core')
    implementation project(':jagratha-ui')

    implementation libs.spring.boot.starter.webflux
    implementation libs.spring.boot.starter.validation
    implementation libs.spring.boot.starter.actuator

    compileOnly libs.lombok
    annotationProcessor libs.spring.boot.configuration.processor
    annotationProcessor libs.lombok

    testImplementation libs.spring.boot.starter.test
    testImplementation libs.reactor.test
}

graalvmNative {
    binaries {
        main {
            imageName = 'jagratha'
            mainClass = 'com.infenia.jagratha.JagrathaApplication'
            buildArgs.add('--no-fallback')
        }
    }
}
