plugins {
    id 'com.infenia.jagratha.java-conventions'
    id 'com.infenia.jagratha.quality-conventions'
    id 'com.infenia.jagratha.jacoco-conventions'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
    alias(libs.plugins.graalvm.buildtools.native)
}

dependencies {
    implementation project(':jagratha-core')
    implementation project(':jagratha-ui')

    implementation libs.spring.boot.starter.webflux
    implementation libs.spring.boot.starter.validation
    implementation libs.spring.boot.starter.actuator

    annotationProcessor libs.spring.boot.configuration.processor

    testImplementation libs.reactor.test
}

graalvmNative {
    binaries {
        main {
            imageName = 'jagratha'
            mainClass = 'com.infenia.jagratha.JagrathaApplication'
            buildArgs.add('--no-fallback')
        }
    }
}
