plugins {
    id 'com.infenia.jagratha.java-conventions'
    id 'com.infenia.jagratha.quality-conventions'
    id 'com.infenia.jagratha.jacoco-conventions'
}

version = '1.0.0'

dependencies {
    implementation project(':jagratha-plugin-api')
    implementation libs.spring.boot.starter
    implementation libs.jackson.dataformat.yaml
}
