gg:
  jte:
    developmentMode: true
    usePrecompiledTemplates: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    default: dev
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: "off"
  ai:
    mcp:
      server:
        name: yukta
        version: 0.0.1
        stdio: true
  docker:
    compose:
      enabled: false


