# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Infenia Private Limited

spring:
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: "off"
  ai:
    mcp:
      server:
        name: yukta
        version: 0.0.1
        protocol: STATELESS
        type: ASYNC
        streamable-http:
          mcp-endpoint: /sse
  docker:
    compose:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.web: DEBUG

gg:
  jte:
    developmentMode: true
    usePrecompiledTemplates: false
    trimControlStructures: true
    template-location: ../ui/src/main/jte
