spring:
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: "off"
  ai:
    mcp:
      server:
        name: jagratha
        version: 0.0.1
        stdio: true
  docker:
    compose:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.web: DEBUG

gg:
  jte:
    developmentMode: false
    usePrecompiledTemplates: true
