spring:
  main:
    banner-mode: "off"
  ai:
    mcp:
      server:
        name: jagratha
        version: 0.0.1
        stdio: true

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.web: DEBUG

jte:
  usePrecompiledTemplates: true
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n%wEx"

app:
  execution-timeout: 300
  logs:
    modified-file: "${user.home}/.jagratha/modified-files"
    results: "${user.home}/.jagratha/results"
