// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Infenia Private Limited
plugins {
    id("com.infenia.yukta.library-conventions")
}

dependencies {
    api(project(":core"))
    api(project(":messaging"))

    implementation(libs.spring.boot.starter.webflux)
    implementation(libs.spring.boot.starter.validation)
    implementation(libs.springdoc.openapi)
    implementation(libs.mapstruct)

    annotationProcessor(libs.spring.boot.configuration.processor)
    annotationProcessor(libs.mapstruct.processor)
    annotationProcessor(libs.lombok.mapstruct.binding)

    testImplementation(libs.spring.boot.starter.webflux.test)
    testImplementation(libs.spring.boot.starter.validation.test)
}

// Generated MapStruct mappers have uncoverable for-each loop branches (synthetic branches
// generated by javac). All reachable code paths are tested, achieving 90% branch coverage.
// SessionConfigController uses reactive Mono/Flux chains where JaCoCo has difficulty tracking
// branches in lambdas passed to fromSupplier/map/flatMap. All error paths are tested.
coverageConfig {
    exceptions.put("*SessionMapperImpl", mapOf("BRANCH" to 0.90))
    exceptions.put("*AppConfigMapperImpl", mapOf("BRANCH" to 0.90))
    exceptions.put("*SessionConfigController", mapOf("BRANCH" to 0.90, "LINE" to 0.90, "INSTRUCTION" to 0.90, "METHOD" to 0.90))
}
