/*
 * Copyright 2026 Infenia Private Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// SPDX-License-Identifier: Apache-2.0
plugins {
    id("com.infenia.yukta.library-conventions")
}

dependencies {
    api(project(":core"))
    api(project(":messaging"))

    implementation(libs.spring.boot.starter.webflux)
    implementation(libs.spring.boot.starter.validation)
    implementation(libs.springdoc.openapi)
    implementation(libs.mapstruct)

    annotationProcessor(libs.spring.boot.configuration.processor)
    annotationProcessor(libs.mapstruct.processor)
    annotationProcessor(libs.lombok.mapstruct.binding)

    testImplementation(libs.spring.boot.starter.webflux.test)
    testImplementation(libs.spring.boot.starter.validation.test)
}

// Generated MapStruct mappers have uncoverable for-each loop branches (synthetic branches
// generated by javac). All reachable code paths are tested, achieving 90% branch coverage.
coverageConfig {
    exceptions.put("*SessionMapperImpl", mapOf("BRANCH" to 0.90))
    exceptions.put("*AppConfigMapperImpl", mapOf("BRANCH" to 0.90))
}
